on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: last_tag
        run: echo "::set-output name=name::$(git ls-remote -q -t | tail -n2 | head -n1 | awk '{ print $NF }')"

      - name: Last tag
        run: echo "last - ${{ steps.last_tag.name }} current - ${{ github.ref }}"
