on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    container: singledigital/bay-ci-builder:3.x
    steps:
      - uses: octokit/request-action@v2.x
        id: get_latest_release
        with:
          route: GET /repos/steveworley/actions-tags/releases
          owner: steveworley
          repo: actions-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - run: |
          latest=$(echo "${{ steps.get_latest_release.outputs.data }}" | gojq '.[1].tag_name')
          echo "$latest"
