on:
  - push

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - id: last_tag
        run: echo "::set-output name=name::$(git ls-remote -q -t | tail -n2 | head -n1 | awk '{ print $NF }' | awk -F '/' '{ print $3 }')"

      - name: Last tag
        run: echo "last - ${{ steps.last_tag.outputs.name }} current - ${{ github.ref }}"

      - name: Diff
        run: git diff origin/${{ steps.last_tag.outputs.name }}...${{ github.ref }}
