on:
  - push

jobs:
  logLatestRelease:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: git fetch --all

      - id: last_tag
        run: echo "::set-output name=name::$(git tag -l --sort=-creatordate --format='%(refname:short)' | head -n2 | tail -n1)"

      - name: Last tag
        run: echo "last - ${{ steps.last_tag.outputs.name }} current - ${{ github.ref }}"

      - name: Diff
        run: git diff ${{ steps.last_tag.outputs.name }} --name-only
